### ISSUE TITLE
presence of json entry in the meta table

### ISSUE THREAD

**Issue by remster** [mapbox/mbview#76]
It appears mbview will *not* render mbtile files which lack this kind of entry in the meta table:
```
json: {"vector_layers": [ { "id": "foo", "description": "", "minzoom": 0, "maxzoom": 15, "fields": {"bar": "String"} } ] }
```
this is the error i see:
```
TypeError: <foo>/mbview/views/vector.ejs:105
    103|     });
    104| 
 >> 105|     <% include layers %>
    106| 
    107|   <% }); %>
    108| });

<foo>/mbview/views/layers.ejs:1
 >> 1| <% sources[sid].vector_layers.forEach(function (layer) { %>
    2| 
    3|   var layerColor = '#' + randomColor(lightColors);
    4| 

Cannot read property 'forEach' of undefined
    at eval (eval at compile (<foo>/mbview/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:55:35)
    at eval (eval at compile (<foo>/mbview/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:112:10)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (<foo>/mbview/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:36:29)
    at returnedFn (<foo>/mbview/node_modules/ejs/lib/ejs.js:580:17)
    at tryHandleCache (<foo>/mbview/node_modules/ejs/lib/ejs.js:223:34)
    at View.exports.renderFile [as engine] (<foo>/mbview/node_modules/ejs/lib/ejs.js:437:10)
    at View.render (<foo>/mbview/node_modules/express/lib/view.js:135:8)
    at tryRender (<foo>/mbview/node_modules/express/lib/application.js:640:10)
    at Function.render (<foo>/mbview/node_modules/express/lib/application.js:592:3)
```
However, the [mbtile spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md) makes no mention of this row.

I find filling the "fields" entry problematic. For every layer key it should state the type of the value. Yet, the [mapbox vector tile spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) doesn't prevent a layer key to have multiple values. One feature in the layer can say: "id": 1234 and another "id" : "ABCD"
and thus it is not true that a value under a key has a distinct type.

**Comment by mattficke** [comment]
This is clarified in the MBTiles 1.3 spec: https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector_layers

The `vector_layers` key is required, and fields that do not have a consistent type should be listed as `"String"`.

>The JSON object in the json row MUST contain a vector_layers key, whose value is an array of JSON objects. Each of those JSON objects describes one layer of vector tile data, and MUST contain the following key-value pairs:
>
>id (string): The layer ID, which is referred to as the name of the layer in the Mapbox Vector Tile spec.
fields (object): A JSON object whose keys and values are the names and types of attributes available in this layer. Each type MUST be the string "Number", "Boolean", or "String". Attributes whose type varies between features SHOULD be listed as "String".
